version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: glass_factory_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=glass_factory
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 